### PR TITLE
Implement Red Hat's Shenandoah GC parsing

### PR DESCRIPTION
**Pull request by ophillan**
Added Shenandoah GC log parsing functionality to GCViewer. Currently parsing all 6 main GC events of Shenandoah - initial mark, final mark, concurrent marking, concurrent evacuation, concurrent reset and allocation failure events. Due to concurrent evacuation, some of the statistics displayed in previous parsers are not used in Shenandoah parser.

This is a part of my BSc thesis in University of Tartu, Estonia. 

EDIT: Currently supports the default -Xlog configuration, i.e. the equivalent of: -Xlog:all=warning:stderr:uptime,level,tags.

More info:
[Shenandoah's OpenJDK wiki](https://wiki.openjdk.java.net/display/shenandoah/Main)
[Building latest OpenJDK9 (with Shenandoah GC)](http://arturmkrtchyan.com/building-openjdk-9-on-ubuntu)

Since it might be a hassle to set up OpenJDK just for this, added logs for testing:
[shenandoah_GC_artificial_memory_leak_logs.txt](https://github.com/chewiebug/GCViewer/files/990979/shenandoah_GC_leak_logs.txt)
[shenandoah_GC_logs.txt](https://github.com/chewiebug/GCViewer/files/990978/shenandoah_GC_logs.txt)

### CODE REVIEW

**Comment by ecki** [comment]
Very cool Mart. Does it ignore datetimestamps? Maybe we need some common infrastructure for Java 9 unified GC Logs.

**Comment by chewiebug** [comment]
@Bernd: should it ignore datetimestamps?

And yes: The more gc algorithms with unified logging should be supported, the more need for common infrastructure / tools will arise. Probably it is best to go step by step and see what's needed, when more algorithms are added. 



-------- Original Message --------

**Comment by ophillan** [comment]
Currently supports the default configuration of Xlog, i.e. the format 
[575.239s][info][gc                      ] GC(2243) Pause Final Mark 7934M->7671M(8192M) 52.606ms

With -Xlog::filename:timenanos datetimestamps can be displayed as 
[2017-05-10T20:06:18.062+0000] GC(10) Pause Final Mark 119M->119M(128M) 0.618ms

That can be easily added, if deemed necessary.

**Comment by shipilev** [comment]
A few comments, which might be addressed later:
a) Shenandoah also has the 8u version, the output there is more in line with other 8u GCs, not Unified Logging. I would expect 8u version to be more popular for a while;
b) Shenandoah output had changed slightly very recently with the addition of "Update References" phase, and making "Concurrent Reset Bitmaps" report the heap occupancies. See the wiki for sample output;

**Comment by chewiebug** [comment]
@ophillan by the way: I'll do the 1.35 release sometime during the next few weeks. After that, I'll merge your pull request. 

@shipilev thank you for your comments. I will merge this pull request as it is to have preliminary support for Shenandoah. Improvements like the ones you mention can be added later.

**Comment by shipilev** [comment]
No problem with me. Ask away if you need any Shenandoah-specific questions answered.

**Comment by shipilev** [comment]
"Pause Full (System.gc())" is another frequent event.

**Pull request merged**
