### PR TITLE
Use native FileDialog on OSX

### PR DESCRIPTION
**Pull request by cgrinds**
Incorporated chewiebug feedback

### CODE REVIEW

**Comment by chewiebug** [comment]
Thanks for including my feedback! Usually, it should not be necessary to open a new pull request to incorporate changes. Using a feature branch to base the pull request on, is a very good idea, however.

**Comment by cgrinds** [comment]
Yeah, I decided to redo in a feature branch to make merging easier.

**Comment by chewiebug** [comment]
Hi Chris,

I have finally merged your branch to develop. Thank you very much for your contribution!

Best regards,
Jörg

**Comment by chewiebug** [comment]
fixes #117

**Pull request closed without merging**
