### PR TITLE
Add new type in AbstractGCEvent

### PR DESCRIPTION
**Pull request by krzysztofburek**

### CODE REVIEW

**Comment by chewiebug** [comment]
Would you have a sample of a log file with this event? Something like this: https://github.com/chewiebug/GCViewer/blob/develop/src/test/resources/openjdk/SampleSun1_8_0G1HumongousMixed.txt

**Comment by krzysztofburek** [comment]
Look at 7395 line:

177824.903: [GC pause (System.gc()) (young) (initial-mark)

2018-07-26 22:16 GMT+02:00 chewiebug <notifications@github.com>:

**Comment by chewiebug** [comment]
Did you attach the file you are referencing?

**Comment by krzysztofburek** [comment]
I send you file logi.gc

sob., 28 lip 2018, 09:30 użytkownik chewiebug <notifications@github.com>
napisał:

**Comment by chewiebug** [comment]
I am sorry, I must be somewhat blind ;-). I can't find the file. Where 
did you send it to?

**Comment by krzysztofburek** [comment]
[logi.zip](https://github.com/chewiebug/GCViewer/files/2244103/logi.zip)

I sent an email earlier

**Comment by chewiebug** [comment]
Hi Krzysztof

Thank you for the logfile and your contribution! Thanks to the logfile, 
I could generalise the handling of System.gc() events for Oracle / 
OpenJDK gc logs!

I have added your name to the list of contributors and merged your pull 
request. You may download the latest build containing your contribution 
here: https://github.com/chewiebug/GCViewer/wiki/Changelog

Best regards,
Jörg

**Pull request merged**
